cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: cozystates-bucket-01
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'